### ISSUE TITLE
Displayed greed value doesn't update until you release the range slider

### ISSUE THREAD

**Issue by Austin-Scott** [Madministrator/steganography#12]
This is simply a quality of life improvement that would be nice to have but not crucial to the functionality of the application. When you are adjusting the greed value the displayed number doesn't update until you release the slider. It would be really nice if that value updated while you are sliding it.

**Comment by Madministrator** [comment]
This was fixed with the most recent merge into master, where I replaced the GUI with Bootstrap.

**Comment by Austin-Scott** [comment]
Looking good! 👍
