### ISSUE TITLE
Canvas Image Convertions Lose Data

### ISSUE THREAD

**Issue by Austin-Scott** [Madministrator/steganography#5]
Drawing to the canvas is a lossy operation. We currently use the canvas to get the pixel data for our images but when I tested the code the the resulting images are garbled. I then did a quick web search that confirmed my suspicion: [Example 1](https://stackoverflow.com/questions/43412842/reconstruct-original-16-bit-raw-pixel-data-from-the-html5-canvas) [Example 2](https://stackoverflow.com/questions/11477673/how-to-create-a-lossless-webp-image-using-todataurl). Due to rounding errors drawing anything in any format to the canvas loses data. We can only use the canvas to convert between jpeg to png. We need a different approach for encoding/decoding our images.

**Comment by Austin-Scott** [comment]
It looks like we will need to use one of the many Javascript PNG encoder/decoder libraries such as [pngjs](https://github.com/lukeapage/pngjs).

**Comment by Austin-Scott** [comment]
Can someone try to get this to work? Either we need someway to covert back-and-forth between [Image](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image) objects and [BasicImage](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/JavaScript%20Hide%20Image/BasicImage.js) without losing any data or someway to read/write PNG files to-and-from [BasicImage](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/JavaScript%20Hide%20Image/BasicImage.js) objects without losing any data.

**Comment by Austin-Scott** [comment]
If I get more time I'll do some more testing to confirm that it is the canvas drawing specifically that is causing us to lose data and not the base64 image representation on line 52 of [StandardizeImageFormat.js](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/StandardizeImageFormat.js).

**Comment by Austin-Scott** [comment]
Still needs to be tested but by using [Blobs](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and the [UPNG Library](https://github.com/photopea/UPNG.js) I just added a possible solution. The new code is in the [StandardizeImageFormat.js file](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/StandardizeImageFormat.js). Feel free to ask any questions and write test code for these functions if you have free time, my schedule is pretty bogged down these next few days.

**Comment by verbert1712** [comment]
I'll try my best to test these functions if I have time, and I'll let you know what I find out!


Tanner Verber

Applied Mathematics and Computer Science

University of Wisconsin Stout

________________________________

**Comment by Austin-Scott** [comment]
I managed to find time to test the new functions. We have a solution! :D We also now have a working JavaScript prototype. Check out [testHideImage.html](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/testHideImage.html) and [testFindImage.html](https://github.com/Madministrator/steganography/blob/Back-End-JavaScript/testFindImage.html) to see the code in action! Now all we need to do is write super similar functions for when we are working with text files and hook up the backend to the front end! 😄

**Comment by verbert1712** [comment]
Awesome! Thank you!


Tanner Verber

Applied Mathematics and Computer Science

University of Wisconsin Stout

________________________________
