### ISSUE TITLE
The color picker is not working at all on Firefox and is only partially working on Chrome

### ISSUE THREAD

**Issue by Austin-Scott** [Madministrator/steganography#8]
![error1](https://user-images.githubusercontent.com/12504656/49970473-0e94b400-fef1-11e8-8683-65899ee39c6b.PNG)
This is what I see on Firefox. The X and Y coordinates are not zero in the upper left hand corner of the page. All of the RGBA values are listed as "undefined". 
![error2](https://user-images.githubusercontent.com/12504656/49970536-43a10680-fef1-11e8-89e4-00b4d5481b48.PNG)
And this is what I see on Chrome. The RGBA values appear to be correct and the coordinates are correct but only one of the magnifying glasses are working. Can you please try to fix the bug and figure out why it is not working at all on Firefox?

**Comment by Drabynoops** [comment]
@Austin-Scott I can't reproduce this error. Is there any console output that you can provide that might shed light on the issue?

If you can also direct me to the files being used. Whether they are in the repo or not, etc.)

I have tested both Firefox and Chrome.

**Comment by Drabynoops** [comment]
Found it! The conditions to reproduce are very strange for me, but I'll work on finding what's causing it.
